### ISSUE TITLE
fail to make on Kali linux with clang compiler

### ISSUE THREAD

**Issue by yyy-git** [riejohnson/cfg-gan#1]
version of my g++ is 7.3.0. nvcc complains no supported g++ and suggests using clang instead. 

The result of make is lots of warnings and errors as follow...

/usr/bin/nvcc -ccbin clang-4.0 src/img/main_cfg.cpp src/img/AzpG_ClasEval.cpp src/img/AzpMain_Cfg.cpp src/img/AzpG_Tools.cpp src/img/AzpG_Cfg.cpp src/nnet/AzpPatchDflt.cpp src/nnet/AzpReNet.cpp src/nnet/AzpReLayer.cpp src/nnet/AzMultiConn.cpp src/nnet/AzpMain_reNet.cpp src/nnet/AzpLmSgd.cpp src/nnet/AzPmat.cpp src/nnet/AzPmatSpa.cpp src/nnet/AzPmatApp.cpp src/nnet/AzPmat_gpu.cu src/nnet/AzPmatSpa_gpu.cu src/nnet/AzCuda_Pmat.cu src/nnet/AzCuda_PmatSpa.cu src/nnet/AzCuda_PmatApp.cu src/nnet/AzpEv.cpp src/nnet/AzpLossDflt.cpp src/com/AzUtil.cpp src/com/AzDmat.cpp src/com/AzParam.cpp src/com/AzSmat.cpp src/com/AzStrPool.cpp src/com/AzTextMat.cpp src/com/AzTools.cpp -Isrc/com -Isrc/data -Isrc/nnet  -D__AZ_SMAT_SINGLE__ -D__AZ_GPU__  -I/usr/include -O2 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_53,code=sm_53 -gencode arch=compute_60,code=sm_60 -o ./cfgexe -L/usr/lib64 -lcudart -lcublas -lcurand -lcusparse
In file included from src/img/main_cfg.cpp:3:
In file included from src/img/AzpMain_Cfg.hpp:22:
In file included from src/nnet/AzpMain_reNet.hpp:25:
In file included from src/nnet/AzpDataSetDflt.hpp:21:
In file included from src/nnet/AzpData_.hpp:23:
In file included from src/nnet/AzPmat.hpp:27:
In file included from src/nnet/AzPmat_gpu.cuh:26:
src/com/AzParam.hpp:243:49: error: use of undeclared identifier 'cpfx'
      throw new AzException(AzInputError, eyec, cpfx(valname,pfx,s), "mu...
                                                ^
src/com/AzParam.hpp:250:49: error: use of undeclared identifier 'cpfx'
      throw new AzException(AzInputError, eyec, cpfx(valname,pfx,s), "mu...
                                                ^
src/com/AzParam.hpp:252:4: error: expected ';' after class
  }
   ^
   ;
src/com/AzParam.hpp:256:49: error: use of undeclared identifier 'cpfx'
      throw new AzException(AzInputError, eyec, cpfx(valname,pfx,s_wrk)...
                                                ^
src/com/AzParam.hpp:260:25: warning: '&&' within '||' [-Wlogical-op-parentheses]
    if (s0.length() > 0 && s1.length() > 0 || s0.length () <= 0 && s1.le...
        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~ ~~
src/com/AzParam.hpp:260:25: note: place parentheses around the '&&' expression
      to silence this warning
    if (s0.length() > 0 && s1.length() > 0 || s0.length () <= 0 && s1.le...
                        ^
        (                                 )
src/com/AzParam.hpp:260:65: warning: '&&' within '||' [-Wlogical-op-parentheses]
  ...> 0 && s1.length() > 0 || s0.length () <= 0 && s1.length() <= 0) {
                            ~~ ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
src/com/AzParam.hpp:260:65: note: place parentheses around the '&&' expression
      to silence this warning
  ...> 0 && s1.length() > 0 || s0.length () <= 0 && s1.length() <= 0) {
                                                 ^
                               (                                    )
src/com/AzParam.hpp:262:43: error: use of undeclared identifier 'cpfx'
      AzBytArr s("Specify either "); s << cpfx(nm0,pfx,s_wrk0) << " or ...
                                          ^
src/com/AzParam.hpp:262:77: error: use of undeclared identifier 'cpfx'
  ...s("Specify either "); s << cpfx(nm0,pfx,s_wrk0) << " or " << cpfx(nm1,pf...
                                                                  ^
src/com/AzParam.hpp:270:57: error: use of undeclared identifier 'cpfx'
    AzBytArr s("Mutually-exclusive parameters: "); s << cpfx(nm0,pfx,s_w...
                                                        ^
src/com/AzParam.hpp:270:92: error: use of undeclared identifier 'cpfx'
  ...parameters: "); s << cpfx(nm0,pfx,s_wrk0) << " and " << cpfx(nm1,pfx,s_w...
                                                             ^
src/com/AzParam.hpp:302:1: error: expected unqualified-id
protected:   
^
src/com/AzParam.hpp:308:1: error: extraneous closing brace ('}')
};
^
In file included from src/img/main_cfg.cpp:3:
In file included from src/img/AzpMain_Cfg.hpp:22:
In file included from src/nnet/AzpMain_reNet.hpp:25:
In file included from src/nnet/AzpDataSetDflt.hpp:21:
In file included from src/nnet/AzpData_.hpp:23:
In file included from src/nnet/AzPmat.hpp:27:
src/nnet/AzPmat_gpu.cuh:248:5: error: no member named 'invalid_input' in 'AzXi';
      did you mean simply 'invalid_input'?
    AzXi::invalid_input(max_threads>maxBlockDimX, eyec, kw_max_threads); 
    ^~~~~~~~~~~~~~~~~~~
    invalid_input
src/com/AzParam.hpp:274:15: note: 'invalid_input' declared here
  static void invalid_input(bool cond, const char *eyec, const char *ite...
              ^
In file included from src/img/main_cfg.cpp:3:
In file included from src/img/AzpMain_Cfg.hpp:22:
In file included from src/nnet/AzpMain_reNet.hpp:25:
In file included from src/nnet/AzpDataSetDflt.hpp:21:
In file included from src/nnet/AzpData_.hpp:23:
In file included from src/nnet/AzPmat.hpp:27:
src/nnet/AzPmat_gpu.cuh:249:5: error: no member named 'invalid_input' in 'AzXi';
      did you mean simply 'invalid_input'?
    AzXi::invalid_input(max_blocks>maxGridDimX, eyec, kw_max_blocks); 
    ^~~~~~~~~~~~~~~~~~~
    invalid_input
src/com/AzParam.hpp:274:15: note: 'invalid_input' declared here
  static void invalid_input(bool cond, const char *eyec, const char *ite...
              ^
In file included from src/img/main_cfg.cpp:3:
In file included from src/img/AzpMain_Cfg.hpp:22:
In file included from src/nnet/AzpMain_reNet.hpp:25:
In file included from src/nnet/AzpDataSetDflt.hpp:21:
In file included from src/nnet/AzpData_.hpp:28:
src/com/AzTextMat.hpp:111:37: warning: '&&' within '||'
      [-Wlogical-op-parentheses]
    if (*str == '\0' || *str >= '0' && *str <= '9' || 
                     ~~ ~~~~~~~~~~~~^~~~~~~~~~~~~~
src/com/AzTextMat.hpp:111:37: note: place parentheses around the '&&' expression
      to silence this warning
    if (*str == '\0' || *str >= '0' && *str <= '9' || 
                                    ^
                        (                         )
src/com/AzTextMat.hpp:123:21: warning: '&&' within '||'
      [-Wlogical-op-parentheses]
    if (*str >= '0' && *str <= '9' || 
        ~~~~~~~~~~~~^~~~~~~~~~~~~~ ~~
src/com/AzTextMat.hpp:123:21: note: place parentheses around the '&&' expression
      to silence this warning
    if (*str >= '0' && *str <= '9' || 
                    ^
        (                         )
In file included from src/img/main_cfg.cpp:3:
In file included from src/img/AzpMain_Cfg.hpp:22:
In file included from src/nnet/AzpMain_reNet.hpp:25:
In file included from src/nnet/AzpDataSetDflt.hpp:21:
src/nnet/AzpData_.hpp:192:5: error: no member named 'throw_if_empty' in 'AzXi';
      did you mean simply 'throw_if_empty'?
    AzXi::throw_if_empty(s_x_ext, eyec, kw_x_ext); 
    ^~~~~~~~~~~~~~~~~~~~
    throw_if_empty
src/com/AzParam.hpp:253:15: note: 'throw_if_empty' declared here
  static void throw_if_empty(const AzBytArr &s, const char *eyec, const ...
              ^
In file included from src/img/main_cfg.cpp:3:
In file included from src/img/AzpMain_Cfg.hpp:22:
In file included from src/nnet/AzpMain_reNet.hpp:25:
In file included from src/nnet/AzpDataSetDflt.hpp:21:
src/nnet/AzpData_.hpp:193:21: error: no member named 'throw_if_empty' in 'AzXi';
      did you mean simply 'throw_if_empty'?
    if (is_there_y) AzXi::throw_if_empty(s_y_ext, eyec, kw_y_ext); 
                    ^~~~~~~~~~~~~~~~~~~~
                    throw_if_empty
src/com/AzParam.hpp:253:15: note: 'throw_if_empty' declared here
  static void throw_if_empty(const AzBytArr &s, const char *eyec, const ...
              ^
In file included from src/img/main_cfg.cpp:3:
In file included from src/img/AzpMain_Cfg.hpp:22:
In file included from src/nnet/AzpMain_reNet.hpp:25:
In file included from src/nnet/AzpDataSetDflt.hpp:21:
src/nnet/AzpData_.hpp:494:5: error: no member named 'throw_if_empty' in 'AzXi';
      did you mean simply 'throw_if_empty'?
    AzXi::throw_if_empty(s_typ, eyec, kw_datatype); 
    ^~~~~~~~~~~~~~~~~~~~
    throw_if_empty
src/com/AzParam.hpp:253:15: note: 'throw_if_empty' declared here
  static void throw_if_empty(const AzBytArr &s, const char *eyec, const ...
              ^
In file included from src/img/main_cfg.cpp:3:
In file included from src/img/AzpMain_Cfg.hpp:22:
In file included from src/nnet/AzpMain_reNet.hpp:25:
In file included from src/nnet/AzpDataSetDflt.hpp:21:
src/nnet/AzpData_.hpp:497:7: error: no member named 'throw_if_empty' in 'AzXi';
      did you mean simply 'throw_if_empty'?
      AzXi::throw_if_empty(s_trnnm, eyec, kw_trnnm);
      ^~~~~~~~~~~~~~~~~~~~
      throw_if_empty

**Comment by riejohnson** [comment]
Can you use gcc version 4 or 5 instead of clang?

You're getting errors that you shouldn't get (e.g., failing to recognize a member function 'cpfx' declared right there), and so I guess something is terribly wrong.  The LVMM website says "Note that clang does not support the CUDA toolkit as installed by many Linux package managers", so there might be something tricky about using clang with nvcc.

I've been using gcc 4 or 5 on Ubuntu and CentOS 7 without any problem.

**Comment by yyy-git** [comment]
Thank you. I will try gcc 4 or 5 later

**Comment by yyy-git** [comment]
I installed g++-4.9 and changed the makefile

all: $(TARGET1) $(TARGET2) $(TARGET3)
$(TARGET1): 
	rm -f $(TARGET1)
	$(CUDA_BIN_PATH)/nvcc -ccbin /usr/bin/g++-4.9 $(CPP_FILES1) $(CFLAGS1) -o $(TARGET1) $(LDFLAGS1)

$(TARGET2):
	rm -f $(TARGET2)
	/usr/bin/g++-4.9 $(CPP_FILES2)  $(CFLAGS2) -o $(TARGET2)

now there is no complain when compiling. But I am not sure whether the result of test.sh is right, and it seems to be using the GTX1050TI rather than GTX1080TI on my machine. the full output is in the txt file.( em... It is using the GTX1080TI, everything goes well.)
[cfg-gan.txt](https://github.com/riejohnson/cfg-gan/files/2419420/cfg-gan.txt)


Wed Sep 26 18:55:38 2018: Checking the mapping ... 
Wed Sep 26 18:55:38 2018: Checking the mapping of layers ... 
g:outdim=1
Wed Sep 26 18:55:38 2018: Initiazing the approximator ... 
AzpG_Cfg::get_size,size=1024
Wed Sep 26 18:55:39 2018: Training loop ... 
Wed Sep 26 18:55:39 2018: g_upd=10 clk=0.868819 Dreal-Dgen=3.70627 c,640
Wed Sep 26 18:55:41 2018: g_upd=20 clk=1.90129 Dreal-Dgen=6.45527 c,640
Wed Sep 26 18:55:42 2018: g_upd=30 clk=2.943 Dreal-Dgen=2.71992 c,640
Wed Sep 26 18:55:43 2018: g_upd=40 clk=3.99633 Dreal-Dgen=0.829633 c,640
Wed Sep 26 18:55:44 2018: g_upd=50 clk=5.05815 Dreal-Dgen=1.2553 c,640
Wed Sep 26 18:55:45 2018: g_upd=60 clk=6.12113 Dreal-Dgen=1.35467 c,640
Wed Sep 26 18:55:46 2018: g_upd=70 clk=7.18778 Dreal-Dgen=1.32891 c,640
Wed Sep 26 18:55:48 2018: g_upd=80 clk=8.25361 Dreal-Dgen=0.747446 c,640
Wed Sep 26 18:55:49 2018: g_upd=90 clk=9.32376 Dreal-Dgen=1.27659 c,640
Wed Sep 26 18:55:50 2018: g_upd=100 clk=10.3975 Dreal-Dgen=1.63794 c,640
Wed Sep 26 18:55:50 2018: Testing ... 
Wed Sep 26 18:55:57 2018: Done with testing ... 
Wed Sep 26 18:55:57 2018: clk,10.3975,12,t,10,d_upd,100,g_upd,100,score,1.09931,Dreal-Dgen,2.1312,Dreal,1.21255,Dgen,-0.91865
Wed Sep 26 18:55:57 2018: Reached the maximum time ... exiting ... 
Wed Sep 26 18:55:57 2018: Done ...
elapsed: 19, 18.407

.....

MaxThreadsPerBlock=1024
MaxBlockDimX=1024
MaxGridDimX=2147483647
MaxSharedMemoryPerBlock=49152
Allocating device memory: 4.29497e+09
Using GPU#0

.......

*/Download/cfg-gan-master/test# nvidia-smi 
Wed Sep 26 19:02:13 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.77                 Driver Version: 390.77                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:0A:00.0 Off |                  N/A |
| 35%   26C    P8    N/A /  75W |      2MiB /  4040MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:41:00.0  On |                  N/A |
|  0%   41C    P8    14W / 280W |    398MiB / 11173MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by riejohnson** [comment]
All the shell scripts are set so that the default GPU (#0) is used. This is done in the following line. 

`gpu=-1 # gpu#.  -1 means "use default"`
  
You can use GPU#1 by changing it to `gpu=1`.  

The compute capability of GeForce GTX 1050 and 1080 is 6.1.  Your test.sh output looks fine (it's supposed to complain if, e.g., your machine doesn't have a GPU), but I think still it's better to match the compute capability.  How about adding  `gencode arch=compute_61,code=sm_61` to the makefile?  

cfg-dcganx.sh is set up to actually generate images.
